version: '2'
services:
  travis:
    build:
      dockerfile: .travis/Dockerfile
      context: .
    volumes:
      - ./:/kinetic/src/mas_domestic_robotics
    image: bitbots-travis
    command: ["bash", "-c", "cd /kinetic && catkin build -c"]
  domestic:
    build: .
    image: bitbots-domestic
