version: '2'
services:
  travis:
    build:
      dockerfile: .travis/Dockerfile
      context: .
    image: bitbots/bitbots-domestic:${TRAVIS_COMMIT}
  domestic:
    build: .
    image: bitbots/bitbots-domestic:kinetic
