# Description: Defines a state machine for a RoboCup@Home "where is this" scenario
# Author: Patrick Nagel
# Email: patrick.nagel@h-brs.de
sm_id: mdr_where_is_this
states: [RECEIVE_INFORMATION_FROM_OPERATOR, PROVIDE_LOCATION_INFORMATION, GIVE_DIRECTIONS, MOVE_TO_OBJECT_LOCATION, DESCRIBE_LOCATION]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: RECEIVE_INFORMATION_FROM_OPERATOR
        state_module_name: mdr_where_is_this.scenario_states.receive_information
        state_class_name: ReceiveInformation
        transitions:
            - transition:
                name: succeeded
                state: PROVIDE_LOCATION_INFORMATION
            - transition:
                name: failed
                state: RECEIVE_INFORMATION_FROM_OPERATOR
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PROVIDE_LOCATION_INFORMATION
        state_module_name: mdr_where_is_this.scenario_states.provide_location_information
        state_class_name: ProvideLocationInformation
        transitions:
            - transition:
                name: succeeded
                state: GIVE_DIRECTIONS
            - transition:
                name: failed
                state: PROVIDE_LOCATION_INFORMATION
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: GIVE_DIRECTIONS
        state_module_name: mdr_where_is_this.scenario_states.give_directions
        state_class_name: GiveDirections
        transitions:
            - transition:
                name: succeeded
                state: MOVE_TO_OBJECT_LOCATION
            - transition:
                name: failed
                state: GIVE_DIRECTIONS
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: MOVE_TO_OBJECT_LOCATION
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: DESCRIBE_LOCATION
            - transition:
                name: failed
                state: MOVE_TO_OBJECT_LOCATION
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 5
    - state:
        name: DESCRIBE_LOCATION
        state_module_name: mdr_where_is_this.scenario_states.describe_location
        state_class_name: DescribeLocation
        transitions:
            - transition:
                name: succeeded
                state: DONE
            - transition:
                name: failed
                state: DESCRIBE_LOCATION
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
